### ISSUE TITLE
ability to create a new folder

### ISSUE THREAD

**Issue by bmccann36** [Ogdentrod/reMarkable-typescript#10]
as far as I can tell there is no method to create a folder. I want to do this for a project I'm working on. It's pretty simple and almost the same as creating a document. Happy to make a PR if its a feature worth adding

**Comment by benoitsepe** [comment]
I would be happy to review it if you have the time :) it shouldn't be too complicated, I think you should be able to re-use most of the code of uploadZip()

**Comment by bmccann36** [comment]
@Ogdentrod created a PR and left some comments in a review 
https://github.com/Ogdentrod/reMarkable-typescript/pull/11

**Comment by bmccann36** [comment]
closing this issue since feature was added in the PR
