### ISSUE TITLE
BUG unable to associate a document with a parent folder

### ISSUE THREAD

**Issue by bmccann36** [Ogdentrod/reMarkable-typescript#15]
**expected behavior**
this code should upload a document inside the specified folder
```js
  const uploaded = await client.uploadEPUB(
    'testDoc',
    '9bf66920-a8ed-45ee-98cf-5ba52a860a0f', // file ID
    myFileBuffer,
    '71e70cd9-8d72-5c8b-addc-0d18c74364bc', // folder ID
  );
```
**actual behavior**
- no parentID is sent to the Remarkable API
- the document is uploaded at the root location of cloud storage

this functionality was broken in this commit https://github.com/Ogdentrod/reMarkable-typescript/commit/13c3ad226d58c2b9f8dad061d5af2011cb40ec74

created PR for proposed fix
https://github.com/Ogdentrod/reMarkable-typescript/pull/14/files

**Comment by bmccann36** [comment]
@Ogdentrod 👀

**Comment by benoitsepe** [comment]
Oops! Thanks for the catch!
Merged and published on npm :)
