### ISSUE TITLE
Expand uploadPDF to support going to a directory

### ISSUE THREAD

**Issue by jakemcc** [Ogdentrod/reMarkable-typescript#17]
Hi there,

Thanks for this project. Just a little feature request. It would be great if `uploadPDF` could take an optional `parentId` for shoving those PDFs into a folder.

I'll probably dive in and make the change myself next time I have some time to hack away on a little project I'm working on but thought I'd give a heads up first, in case you felt like knocking it out or knew of some reason why it can't be done.

Thanks!

**Comment by benoitsepe** [comment]
Hi! Done in `remarkable-typescript@1.1.3`
