### ISSUE TITLE
npx tsc fails due to body.Host

### ISSUE THREAD

**Issue by fvirdia** [Ogdentrod/reMarkable-typescript#5]
Hi there,

I recently forked the repository since I'm interested in adding some minor functionality.
Yet, I'm currently unable to build it. Running `npm run prepare` results in
```
> remarkable-typescript@1.0.5 prepare /media/fernando/shared/reMarkable-typescript
> npx tsc

src/remarkable.ts:93:39 - error TS2339: Property 'Host' does not exist on type 'string'.

93     this.storageUrl = `https://${body.Host}`;
                                         ~~~~

src/remarkable.ts:100:42 - error TS2339: Property 'Host' does not exist on type 'string'.

100     this.notificationUrl = `wss://${body.Host}`;
                                             ~~~~
```
It's a minor issue, but I was wondering if it's something that should be changed, since the line has been around since the initial commit, and the build on `npm` runs fine. How was that one compiled?

Cheers
Fernando

**Comment by benoitsepe** [comment]
Hey,

Sorry for the delay

From the output here it seems like reMarkable changed the return object

I will try to take the time to fix it

**Comment by fvirdia** [comment]
thanks dude. If you are interested in keeping the typescript library alive, I may contribute some code I wrote for my desktop client
